// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/core/node/common/service/object_search_permission_update_message.proto

#include "proto/core/node/common/service/object_search_permission_update_message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UID_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fio_2faddress_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Address_proto_2fcore_2fio_2faddress_2eproto;
namespace syft {
namespace core {
namespace node {
namespace common {
namespace service {
class ObjectSearchPermissionUpdateMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ObjectSearchPermissionUpdateMessage> _instance;
} _ObjectSearchPermissionUpdateMessage_default_instance_;
}  // namespace service
}  // namespace common
}  // namespace node
}  // namespace core
}  // namespace syft
static void InitDefaultsscc_info_ObjectSearchPermissionUpdateMessage_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::syft::core::node::common::service::_ObjectSearchPermissionUpdateMessage_default_instance_;
    new (ptr) ::syft::core::node::common::service::ObjectSearchPermissionUpdateMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_ObjectSearchPermissionUpdateMessage_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_ObjectSearchPermissionUpdateMessage_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto}, {
      &scc_info_UID_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto.base,
      &scc_info_Address_proto_2fcore_2fio_2faddress_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::service::ObjectSearchPermissionUpdateMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::service::ObjectSearchPermissionUpdateMessage, msg_id_),
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::service::ObjectSearchPermissionUpdateMessage, address_),
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::service::ObjectSearchPermissionUpdateMessage, target_verify_key_),
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::service::ObjectSearchPermissionUpdateMessage, target_object_id_),
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::service::ObjectSearchPermissionUpdateMessage, add_instead_of_remove_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::syft::core::node::common::service::ObjectSearchPermissionUpdateMessage)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::syft::core::node::common::service::_ObjectSearchPermissionUpdateMessage_default_instance_),
};

const char descriptor_table_protodef_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\nLproto/core/node/common/service/object_"
  "search_permission_update_message.proto\022\035"
  "syft.core.node.common.service\032%proto/cor"
  "e/common/common_object.proto\032\033proto/core"
  "/io/address.proto\"\337\001\n#ObjectSearchPermis"
  "sionUpdateMessage\022%\n\006msg_id\030\001 \001(\0132\025.syft"
  ".core.common.UID\022&\n\007address\030\002 \001(\0132\025.syft"
  ".core.io.Address\022\031\n\021target_verify_key\030\003 "
  "\001(\014\022/\n\020target_object_id\030\004 \001(\0132\025.syft.cor"
  "e.common.UID\022\035\n\025add_instead_of_remove\030\005 "
  "\001(\010b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto_deps[2] = {
  &::descriptor_table_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto,
  &::descriptor_table_proto_2fcore_2fio_2faddress_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto_sccs[1] = {
  &scc_info_ObjectSearchPermissionUpdateMessage_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto = {
  false, false, descriptor_table_protodef_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto, "proto/core/node/common/service/object_search_permission_update_message.proto", 411,
  &descriptor_table_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto_once, descriptor_table_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto_sccs, descriptor_table_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto_deps, 1, 2,
  schemas, file_default_instances, TableStruct_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto::offsets,
  file_level_metadata_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto, 1, file_level_enum_descriptors_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto, file_level_service_descriptors_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto)), true);
namespace syft {
namespace core {
namespace node {
namespace common {
namespace service {

// ===================================================================

class ObjectSearchPermissionUpdateMessage::_Internal {
 public:
  static const ::syft::core::common::UID& msg_id(const ObjectSearchPermissionUpdateMessage* msg);
  static const ::syft::core::io::Address& address(const ObjectSearchPermissionUpdateMessage* msg);
  static const ::syft::core::common::UID& target_object_id(const ObjectSearchPermissionUpdateMessage* msg);
};

const ::syft::core::common::UID&
ObjectSearchPermissionUpdateMessage::_Internal::msg_id(const ObjectSearchPermissionUpdateMessage* msg) {
  return *msg->msg_id_;
}
const ::syft::core::io::Address&
ObjectSearchPermissionUpdateMessage::_Internal::address(const ObjectSearchPermissionUpdateMessage* msg) {
  return *msg->address_;
}
const ::syft::core::common::UID&
ObjectSearchPermissionUpdateMessage::_Internal::target_object_id(const ObjectSearchPermissionUpdateMessage* msg) {
  return *msg->target_object_id_;
}
void ObjectSearchPermissionUpdateMessage::clear_msg_id() {
  if (GetArena() == nullptr && msg_id_ != nullptr) {
    delete msg_id_;
  }
  msg_id_ = nullptr;
}
void ObjectSearchPermissionUpdateMessage::clear_address() {
  if (GetArena() == nullptr && address_ != nullptr) {
    delete address_;
  }
  address_ = nullptr;
}
void ObjectSearchPermissionUpdateMessage::clear_target_object_id() {
  if (GetArena() == nullptr && target_object_id_ != nullptr) {
    delete target_object_id_;
  }
  target_object_id_ = nullptr;
}
ObjectSearchPermissionUpdateMessage::ObjectSearchPermissionUpdateMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:syft.core.node.common.service.ObjectSearchPermissionUpdateMessage)
}
ObjectSearchPermissionUpdateMessage::ObjectSearchPermissionUpdateMessage(const ObjectSearchPermissionUpdateMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  target_verify_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_target_verify_key().empty()) {
    target_verify_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_target_verify_key(),
      GetArena());
  }
  if (from._internal_has_msg_id()) {
    msg_id_ = new ::syft::core::common::UID(*from.msg_id_);
  } else {
    msg_id_ = nullptr;
  }
  if (from._internal_has_address()) {
    address_ = new ::syft::core::io::Address(*from.address_);
  } else {
    address_ = nullptr;
  }
  if (from._internal_has_target_object_id()) {
    target_object_id_ = new ::syft::core::common::UID(*from.target_object_id_);
  } else {
    target_object_id_ = nullptr;
  }
  add_instead_of_remove_ = from.add_instead_of_remove_;
  // @@protoc_insertion_point(copy_constructor:syft.core.node.common.service.ObjectSearchPermissionUpdateMessage)
}

void ObjectSearchPermissionUpdateMessage::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ObjectSearchPermissionUpdateMessage_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto.base);
  target_verify_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&msg_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&add_instead_of_remove_) -
      reinterpret_cast<char*>(&msg_id_)) + sizeof(add_instead_of_remove_));
}

ObjectSearchPermissionUpdateMessage::~ObjectSearchPermissionUpdateMessage() {
  // @@protoc_insertion_point(destructor:syft.core.node.common.service.ObjectSearchPermissionUpdateMessage)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ObjectSearchPermissionUpdateMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  target_verify_key_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete msg_id_;
  if (this != internal_default_instance()) delete address_;
  if (this != internal_default_instance()) delete target_object_id_;
}

void ObjectSearchPermissionUpdateMessage::ArenaDtor(void* object) {
  ObjectSearchPermissionUpdateMessage* _this = reinterpret_cast< ObjectSearchPermissionUpdateMessage* >(object);
  (void)_this;
}
void ObjectSearchPermissionUpdateMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ObjectSearchPermissionUpdateMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ObjectSearchPermissionUpdateMessage& ObjectSearchPermissionUpdateMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ObjectSearchPermissionUpdateMessage_proto_2fcore_2fnode_2fcommon_2fservice_2fobject_5fsearch_5fpermission_5fupdate_5fmessage_2eproto.base);
  return *internal_default_instance();
}


void ObjectSearchPermissionUpdateMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:syft.core.node.common.service.ObjectSearchPermissionUpdateMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  target_verify_key_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && msg_id_ != nullptr) {
    delete msg_id_;
  }
  msg_id_ = nullptr;
  if (GetArena() == nullptr && address_ != nullptr) {
    delete address_;
  }
  address_ = nullptr;
  if (GetArena() == nullptr && target_object_id_ != nullptr) {
    delete target_object_id_;
  }
  target_object_id_ = nullptr;
  add_instead_of_remove_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ObjectSearchPermissionUpdateMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .syft.core.common.UID msg_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_msg_id(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .syft.core.io.Address address = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_address(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes target_verify_key = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_target_verify_key();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .syft.core.common.UID target_object_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_target_object_id(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool add_instead_of_remove = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          add_instead_of_remove_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ObjectSearchPermissionUpdateMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:syft.core.node.common.service.ObjectSearchPermissionUpdateMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .syft.core.common.UID msg_id = 1;
  if (this->has_msg_id()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::msg_id(this), target, stream);
  }

  // .syft.core.io.Address address = 2;
  if (this->has_address()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::address(this), target, stream);
  }

  // bytes target_verify_key = 3;
  if (this->target_verify_key().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_target_verify_key(), target);
  }

  // .syft.core.common.UID target_object_id = 4;
  if (this->has_target_object_id()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::target_object_id(this), target, stream);
  }

  // bool add_instead_of_remove = 5;
  if (this->add_instead_of_remove() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(5, this->_internal_add_instead_of_remove(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syft.core.node.common.service.ObjectSearchPermissionUpdateMessage)
  return target;
}

size_t ObjectSearchPermissionUpdateMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syft.core.node.common.service.ObjectSearchPermissionUpdateMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes target_verify_key = 3;
  if (this->target_verify_key().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_target_verify_key());
  }

  // .syft.core.common.UID msg_id = 1;
  if (this->has_msg_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *msg_id_);
  }

  // .syft.core.io.Address address = 2;
  if (this->has_address()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *address_);
  }

  // .syft.core.common.UID target_object_id = 4;
  if (this->has_target_object_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *target_object_id_);
  }

  // bool add_instead_of_remove = 5;
  if (this->add_instead_of_remove() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ObjectSearchPermissionUpdateMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syft.core.node.common.service.ObjectSearchPermissionUpdateMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const ObjectSearchPermissionUpdateMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ObjectSearchPermissionUpdateMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syft.core.node.common.service.ObjectSearchPermissionUpdateMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syft.core.node.common.service.ObjectSearchPermissionUpdateMessage)
    MergeFrom(*source);
  }
}

void ObjectSearchPermissionUpdateMessage::MergeFrom(const ObjectSearchPermissionUpdateMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syft.core.node.common.service.ObjectSearchPermissionUpdateMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.target_verify_key().size() > 0) {
    _internal_set_target_verify_key(from._internal_target_verify_key());
  }
  if (from.has_msg_id()) {
    _internal_mutable_msg_id()->::syft::core::common::UID::MergeFrom(from._internal_msg_id());
  }
  if (from.has_address()) {
    _internal_mutable_address()->::syft::core::io::Address::MergeFrom(from._internal_address());
  }
  if (from.has_target_object_id()) {
    _internal_mutable_target_object_id()->::syft::core::common::UID::MergeFrom(from._internal_target_object_id());
  }
  if (from.add_instead_of_remove() != 0) {
    _internal_set_add_instead_of_remove(from._internal_add_instead_of_remove());
  }
}

void ObjectSearchPermissionUpdateMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syft.core.node.common.service.ObjectSearchPermissionUpdateMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ObjectSearchPermissionUpdateMessage::CopyFrom(const ObjectSearchPermissionUpdateMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syft.core.node.common.service.ObjectSearchPermissionUpdateMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObjectSearchPermissionUpdateMessage::IsInitialized() const {
  return true;
}

void ObjectSearchPermissionUpdateMessage::InternalSwap(ObjectSearchPermissionUpdateMessage* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  target_verify_key_.Swap(&other->target_verify_key_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ObjectSearchPermissionUpdateMessage, add_instead_of_remove_)
      + sizeof(ObjectSearchPermissionUpdateMessage::add_instead_of_remove_)
      - PROTOBUF_FIELD_OFFSET(ObjectSearchPermissionUpdateMessage, msg_id_)>(
          reinterpret_cast<char*>(&msg_id_),
          reinterpret_cast<char*>(&other->msg_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ObjectSearchPermissionUpdateMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace service
}  // namespace common
}  // namespace node
}  // namespace core
}  // namespace syft
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::syft::core::node::common::service::ObjectSearchPermissionUpdateMessage* Arena::CreateMaybeMessage< ::syft::core::node::common::service::ObjectSearchPermissionUpdateMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::syft::core::node::common::service::ObjectSearchPermissionUpdateMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
