// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/core/node/common/action/run_class_method.proto

#include "proto/core/node/common/action/run_class_method.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UID_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fio_2faddress_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Address_proto_2fcore_2fio_2faddress_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_RunClassMethodAction_KwargsEntry_DoNotUse_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fpointer_2fpointer_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_Pointer_proto_2fcore_2fpointer_2fpointer_2eproto;
namespace syft {
namespace core {
namespace node {
namespace common {
namespace action {
class RunClassMethodAction_KwargsEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RunClassMethodAction_KwargsEntry_DoNotUse> _instance;
} _RunClassMethodAction_KwargsEntry_DoNotUse_default_instance_;
class RunClassMethodActionDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RunClassMethodAction> _instance;
} _RunClassMethodAction_default_instance_;
}  // namespace action
}  // namespace common
}  // namespace node
}  // namespace core
}  // namespace syft
static void InitDefaultsscc_info_RunClassMethodAction_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::syft::core::node::common::action::_RunClassMethodAction_default_instance_;
    new (ptr) ::syft::core::node::common::action::RunClassMethodAction();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<4> scc_info_RunClassMethodAction_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 4, 0, InitDefaultsscc_info_RunClassMethodAction_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto}, {
      &scc_info_Pointer_proto_2fcore_2fpointer_2fpointer_2eproto.base,
      &scc_info_RunClassMethodAction_KwargsEntry_DoNotUse_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto.base,
      &scc_info_UID_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto.base,
      &scc_info_Address_proto_2fcore_2fio_2faddress_2eproto.base,}};

static void InitDefaultsscc_info_RunClassMethodAction_KwargsEntry_DoNotUse_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::syft::core::node::common::action::_RunClassMethodAction_KwargsEntry_DoNotUse_default_instance_;
    new (ptr) ::syft::core::node::common::action::RunClassMethodAction_KwargsEntry_DoNotUse();
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_RunClassMethodAction_KwargsEntry_DoNotUse_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_RunClassMethodAction_KwargsEntry_DoNotUse_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto}, {
      &scc_info_Pointer_proto_2fcore_2fpointer_2fpointer_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::action::RunClassMethodAction_KwargsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::action::RunClassMethodAction_KwargsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::action::RunClassMethodAction_KwargsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::action::RunClassMethodAction_KwargsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::action::RunClassMethodAction, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::action::RunClassMethodAction, path_),
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::action::RunClassMethodAction, _self_),
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::action::RunClassMethodAction, args_),
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::action::RunClassMethodAction, kwargs_),
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::action::RunClassMethodAction, id_at_location_),
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::action::RunClassMethodAction, address_),
  PROTOBUF_FIELD_OFFSET(::syft::core::node::common::action::RunClassMethodAction, msg_id_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::syft::core::node::common::action::RunClassMethodAction_KwargsEntry_DoNotUse)},
  { 9, -1, sizeof(::syft::core::node::common::action::RunClassMethodAction)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::syft::core::node::common::action::_RunClassMethodAction_KwargsEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::syft::core::node::common::action::_RunClassMethodAction_default_instance_),
};

const char descriptor_table_protodef_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n4proto/core/node/common/action/run_clas"
  "s_method.proto\022\034syft.core.node.common.ac"
  "tion\032%proto/core/common/common_object.pr"
  "oto\032 proto/core/pointer/pointer.proto\032\033p"
  "roto/core/io/address.proto\"\222\003\n\024RunClassM"
  "ethodAction\022\014\n\004path\030\001 \001(\t\022)\n\005_self\030\002 \001(\013"
  "2\032.syft.core.pointer.Pointer\022(\n\004args\030\003 \003"
  "(\0132\032.syft.core.pointer.Pointer\022N\n\006kwargs"
  "\030\004 \003(\0132>.syft.core.node.common.action.Ru"
  "nClassMethodAction.KwargsEntry\022-\n\016id_at_"
  "location\030\005 \001(\0132\025.syft.core.common.UID\022&\n"
  "\007address\030\006 \001(\0132\025.syft.core.io.Address\022%\n"
  "\006msg_id\030\007 \001(\0132\025.syft.core.common.UID\032I\n\013"
  "KwargsEntry\022\013\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(\0132"
  "\032.syft.core.pointer.Pointer:\0028\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto_deps[3] = {
  &::descriptor_table_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto,
  &::descriptor_table_proto_2fcore_2fio_2faddress_2eproto,
  &::descriptor_table_proto_2fcore_2fpointer_2fpointer_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto_sccs[2] = {
  &scc_info_RunClassMethodAction_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto.base,
  &scc_info_RunClassMethodAction_KwargsEntry_DoNotUse_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto = {
  false, false, descriptor_table_protodef_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto, "proto/core/node/common/action/run_class_method.proto", 599,
  &descriptor_table_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto_once, descriptor_table_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto_sccs, descriptor_table_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto_deps, 2, 3,
  schemas, file_default_instances, TableStruct_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto::offsets,
  file_level_metadata_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto, 2, file_level_enum_descriptors_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto, file_level_service_descriptors_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto)), true);
namespace syft {
namespace core {
namespace node {
namespace common {
namespace action {

// ===================================================================

RunClassMethodAction_KwargsEntry_DoNotUse::RunClassMethodAction_KwargsEntry_DoNotUse() {}
RunClassMethodAction_KwargsEntry_DoNotUse::RunClassMethodAction_KwargsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void RunClassMethodAction_KwargsEntry_DoNotUse::MergeFrom(const RunClassMethodAction_KwargsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata RunClassMethodAction_KwargsEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void RunClassMethodAction_KwargsEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

class RunClassMethodAction::_Internal {
 public:
  static const ::syft::core::pointer::Pointer& _self(const RunClassMethodAction* msg);
  static const ::syft::core::common::UID& id_at_location(const RunClassMethodAction* msg);
  static const ::syft::core::io::Address& address(const RunClassMethodAction* msg);
  static const ::syft::core::common::UID& msg_id(const RunClassMethodAction* msg);
};

const ::syft::core::pointer::Pointer&
RunClassMethodAction::_Internal::_self(const RunClassMethodAction* msg) {
  return *msg->_self_;
}
const ::syft::core::common::UID&
RunClassMethodAction::_Internal::id_at_location(const RunClassMethodAction* msg) {
  return *msg->id_at_location_;
}
const ::syft::core::io::Address&
RunClassMethodAction::_Internal::address(const RunClassMethodAction* msg) {
  return *msg->address_;
}
const ::syft::core::common::UID&
RunClassMethodAction::_Internal::msg_id(const RunClassMethodAction* msg) {
  return *msg->msg_id_;
}
void RunClassMethodAction::clear__self() {
  if (GetArena() == nullptr && _self_ != nullptr) {
    delete _self_;
  }
  _self_ = nullptr;
}
void RunClassMethodAction::clear_args() {
  args_.Clear();
}
void RunClassMethodAction::clear_kwargs() {
  kwargs_.Clear();
}
void RunClassMethodAction::clear_id_at_location() {
  if (GetArena() == nullptr && id_at_location_ != nullptr) {
    delete id_at_location_;
  }
  id_at_location_ = nullptr;
}
void RunClassMethodAction::clear_address() {
  if (GetArena() == nullptr && address_ != nullptr) {
    delete address_;
  }
  address_ = nullptr;
}
void RunClassMethodAction::clear_msg_id() {
  if (GetArena() == nullptr && msg_id_ != nullptr) {
    delete msg_id_;
  }
  msg_id_ = nullptr;
}
RunClassMethodAction::RunClassMethodAction(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  args_(arena),
  kwargs_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:syft.core.node.common.action.RunClassMethodAction)
}
RunClassMethodAction::RunClassMethodAction(const RunClassMethodAction& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      args_(from.args_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  kwargs_.MergeFrom(from.kwargs_);
  path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_path().empty()) {
    path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_path(),
      GetArena());
  }
  if (from._internal_has__self()) {
    _self_ = new ::syft::core::pointer::Pointer(*from._self_);
  } else {
    _self_ = nullptr;
  }
  if (from._internal_has_id_at_location()) {
    id_at_location_ = new ::syft::core::common::UID(*from.id_at_location_);
  } else {
    id_at_location_ = nullptr;
  }
  if (from._internal_has_address()) {
    address_ = new ::syft::core::io::Address(*from.address_);
  } else {
    address_ = nullptr;
  }
  if (from._internal_has_msg_id()) {
    msg_id_ = new ::syft::core::common::UID(*from.msg_id_);
  } else {
    msg_id_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:syft.core.node.common.action.RunClassMethodAction)
}

void RunClassMethodAction::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RunClassMethodAction_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto.base);
  path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&_self_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&msg_id_) -
      reinterpret_cast<char*>(&_self_)) + sizeof(msg_id_));
}

RunClassMethodAction::~RunClassMethodAction() {
  // @@protoc_insertion_point(destructor:syft.core.node.common.action.RunClassMethodAction)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RunClassMethodAction::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  path_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete _self_;
  if (this != internal_default_instance()) delete id_at_location_;
  if (this != internal_default_instance()) delete address_;
  if (this != internal_default_instance()) delete msg_id_;
}

void RunClassMethodAction::ArenaDtor(void* object) {
  RunClassMethodAction* _this = reinterpret_cast< RunClassMethodAction* >(object);
  (void)_this;
}
void RunClassMethodAction::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RunClassMethodAction::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RunClassMethodAction& RunClassMethodAction::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RunClassMethodAction_proto_2fcore_2fnode_2fcommon_2faction_2frun_5fclass_5fmethod_2eproto.base);
  return *internal_default_instance();
}


void RunClassMethodAction::Clear() {
// @@protoc_insertion_point(message_clear_start:syft.core.node.common.action.RunClassMethodAction)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  args_.Clear();
  kwargs_.Clear();
  path_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && _self_ != nullptr) {
    delete _self_;
  }
  _self_ = nullptr;
  if (GetArena() == nullptr && id_at_location_ != nullptr) {
    delete id_at_location_;
  }
  id_at_location_ = nullptr;
  if (GetArena() == nullptr && address_ != nullptr) {
    delete address_;
  }
  address_ = nullptr;
  if (GetArena() == nullptr && msg_id_ != nullptr) {
    delete msg_id_;
  }
  msg_id_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RunClassMethodAction::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string path = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_path();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "syft.core.node.common.action.RunClassMethodAction.path"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .syft.core.pointer.Pointer _self = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable__self(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .syft.core.pointer.Pointer args = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_args(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      // map<string, .syft.core.pointer.Pointer> kwargs = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&kwargs_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      // .syft.core.common.UID id_at_location = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_id_at_location(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .syft.core.io.Address address = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_address(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .syft.core.common.UID msg_id = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_msg_id(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RunClassMethodAction::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:syft.core.node.common.action.RunClassMethodAction)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string path = 1;
  if (this->path().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_path().data(), static_cast<int>(this->_internal_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "syft.core.node.common.action.RunClassMethodAction.path");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_path(), target);
  }

  // .syft.core.pointer.Pointer _self = 2;
  if (this->has__self()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::_self(this), target, stream);
  }

  // repeated .syft.core.pointer.Pointer args = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_args_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_args(i), target, stream);
  }

  // map<string, .syft.core.pointer.Pointer> kwargs = 4;
  if (!this->_internal_kwargs().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::syft::core::pointer::Pointer >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "syft.core.node.common.action.RunClassMethodAction.KwargsEntry.key");
      }
    };

    if (stream->IsSerializationDeterministic() &&
        this->_internal_kwargs().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_kwargs().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::syft::core::pointer::Pointer >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::syft::core::pointer::Pointer >::const_iterator
          it = this->_internal_kwargs().begin();
          it != this->_internal_kwargs().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = RunClassMethodAction_KwargsEntry_DoNotUse::Funcs::InternalSerialize(4, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target, stream);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::syft::core::pointer::Pointer >::const_iterator
          it = this->_internal_kwargs().begin();
          it != this->_internal_kwargs().end(); ++it) {
        target = RunClassMethodAction_KwargsEntry_DoNotUse::Funcs::InternalSerialize(4, it->first, it->second, target, stream);
        Utf8Check::Check(&(*it));
      }
    }
  }

  // .syft.core.common.UID id_at_location = 5;
  if (this->has_id_at_location()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::id_at_location(this), target, stream);
  }

  // .syft.core.io.Address address = 6;
  if (this->has_address()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::address(this), target, stream);
  }

  // .syft.core.common.UID msg_id = 7;
  if (this->has_msg_id()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        7, _Internal::msg_id(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syft.core.node.common.action.RunClassMethodAction)
  return target;
}

size_t RunClassMethodAction::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syft.core.node.common.action.RunClassMethodAction)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .syft.core.pointer.Pointer args = 3;
  total_size += 1UL * this->_internal_args_size();
  for (const auto& msg : this->args_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // map<string, .syft.core.pointer.Pointer> kwargs = 4;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_kwargs_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::syft::core::pointer::Pointer >::const_iterator
      it = this->_internal_kwargs().begin();
      it != this->_internal_kwargs().end(); ++it) {
    total_size += RunClassMethodAction_KwargsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // string path = 1;
  if (this->path().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path());
  }

  // .syft.core.pointer.Pointer _self = 2;
  if (this->has__self()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_self_);
  }

  // .syft.core.common.UID id_at_location = 5;
  if (this->has_id_at_location()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *id_at_location_);
  }

  // .syft.core.io.Address address = 6;
  if (this->has_address()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *address_);
  }

  // .syft.core.common.UID msg_id = 7;
  if (this->has_msg_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *msg_id_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RunClassMethodAction::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syft.core.node.common.action.RunClassMethodAction)
  GOOGLE_DCHECK_NE(&from, this);
  const RunClassMethodAction* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RunClassMethodAction>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syft.core.node.common.action.RunClassMethodAction)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syft.core.node.common.action.RunClassMethodAction)
    MergeFrom(*source);
  }
}

void RunClassMethodAction::MergeFrom(const RunClassMethodAction& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syft.core.node.common.action.RunClassMethodAction)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  args_.MergeFrom(from.args_);
  kwargs_.MergeFrom(from.kwargs_);
  if (from.path().size() > 0) {
    _internal_set_path(from._internal_path());
  }
  if (from.has__self()) {
    _internal_mutable__self()->::syft::core::pointer::Pointer::MergeFrom(from._internal__self());
  }
  if (from.has_id_at_location()) {
    _internal_mutable_id_at_location()->::syft::core::common::UID::MergeFrom(from._internal_id_at_location());
  }
  if (from.has_address()) {
    _internal_mutable_address()->::syft::core::io::Address::MergeFrom(from._internal_address());
  }
  if (from.has_msg_id()) {
    _internal_mutable_msg_id()->::syft::core::common::UID::MergeFrom(from._internal_msg_id());
  }
}

void RunClassMethodAction::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syft.core.node.common.action.RunClassMethodAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RunClassMethodAction::CopyFrom(const RunClassMethodAction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syft.core.node.common.action.RunClassMethodAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RunClassMethodAction::IsInitialized() const {
  return true;
}

void RunClassMethodAction::InternalSwap(RunClassMethodAction* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  args_.InternalSwap(&other->args_);
  kwargs_.Swap(&other->kwargs_);
  path_.Swap(&other->path_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RunClassMethodAction, msg_id_)
      + sizeof(RunClassMethodAction::msg_id_)
      - PROTOBUF_FIELD_OFFSET(RunClassMethodAction, _self_)>(
          reinterpret_cast<char*>(&_self_),
          reinterpret_cast<char*>(&other->_self_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RunClassMethodAction::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace action
}  // namespace common
}  // namespace node
}  // namespace core
}  // namespace syft
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::syft::core::node::common::action::RunClassMethodAction_KwargsEntry_DoNotUse* Arena::CreateMaybeMessage< ::syft::core::node::common::action::RunClassMethodAction_KwargsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::syft::core::node::common::action::RunClassMethodAction_KwargsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::syft::core::node::common::action::RunClassMethodAction* Arena::CreateMaybeMessage< ::syft::core::node::common::action::RunClassMethodAction >(Arena* arena) {
  return Arena::CreateMessageInternal< ::syft::core::node::common::action::RunClassMethodAction >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
