// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/core/store/store_object.proto

#include "proto/core/store/store_object.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_google_2fprotobuf_2fany_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Any_google_2fprotobuf_2fany_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UID_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fstore_2fstore_5fobject_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_Container_proto_2fcore_2fstore_2fstore_5fobject_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fstore_2fstore_5fobject_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_DictContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fstore_2fstore_5fobject_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_DictContainer_DictMappingEntry_DoNotUse_proto_2fcore_2fstore_2fstore_5fobject_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fstore_2fstore_5fobject_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GridContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fstore_2fstore_5fobject_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SearchEngine_proto_2fcore_2fstore_2fstore_5fobject_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fstore_2fstore_5fobject_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SqlContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fstore_2fstore_5fobject_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_StorableObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fstore_2fstore_5fobject_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_StoreObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto;
namespace syft {
namespace core {
namespace store {
class StoreGenericObjectDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<StoreGenericObject> _instance;
} _StoreGenericObject_default_instance_;
class StorableObjectDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<StorableObject> _instance;
} _StorableObject_default_instance_;
class StoreObjectDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<StoreObject> _instance;
} _StoreObject_default_instance_;
class ContainerDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Container> _instance;
} _Container_default_instance_;
class SearchEngineDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SearchEngine> _instance;
} _SearchEngine_default_instance_;
class DictContainer_DictMappingEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DictContainer_DictMappingEntry_DoNotUse> _instance;
} _DictContainer_DictMappingEntry_DoNotUse_default_instance_;
class DictContainerDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DictContainer> _instance;
} _DictContainer_default_instance_;
class SqlContainerDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SqlContainer> _instance;
} _SqlContainer_default_instance_;
class GridContainerDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GridContainer> _instance;
} _GridContainer_default_instance_;
}  // namespace store
}  // namespace core
}  // namespace syft
static void InitDefaultsscc_info_Container_proto_2fcore_2fstore_2fstore_5fobject_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::syft::core::store::_Container_default_instance_;
    new (ptr) ::syft::core::store::Container();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_Container_proto_2fcore_2fstore_2fstore_5fobject_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 3, 0, InitDefaultsscc_info_Container_proto_2fcore_2fstore_2fstore_5fobject_2eproto}, {
      &scc_info_DictContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,
      &scc_info_SqlContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,
      &scc_info_GridContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,}};

static void InitDefaultsscc_info_DictContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::syft::core::store::_DictContainer_default_instance_;
    new (ptr) ::syft::core::store::DictContainer();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_DictContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_DictContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto}, {
      &scc_info_DictContainer_DictMappingEntry_DoNotUse_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,}};

static void InitDefaultsscc_info_DictContainer_DictMappingEntry_DoNotUse_proto_2fcore_2fstore_2fstore_5fobject_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::syft::core::store::_DictContainer_DictMappingEntry_DoNotUse_default_instance_;
    new (ptr) ::syft::core::store::DictContainer_DictMappingEntry_DoNotUse();
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_DictContainer_DictMappingEntry_DoNotUse_proto_2fcore_2fstore_2fstore_5fobject_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_DictContainer_DictMappingEntry_DoNotUse_proto_2fcore_2fstore_2fstore_5fobject_2eproto}, {
      &scc_info_Any_google_2fprotobuf_2fany_2eproto.base,}};

static void InitDefaultsscc_info_GridContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::syft::core::store::_GridContainer_default_instance_;
    new (ptr) ::syft::core::store::GridContainer();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GridContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GridContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto}, {}};

static void InitDefaultsscc_info_SearchEngine_proto_2fcore_2fstore_2fstore_5fobject_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::syft::core::store::_SearchEngine_default_instance_;
    new (ptr) ::syft::core::store::SearchEngine();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SearchEngine_proto_2fcore_2fstore_2fstore_5fobject_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SearchEngine_proto_2fcore_2fstore_2fstore_5fobject_2eproto}, {}};

static void InitDefaultsscc_info_SqlContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::syft::core::store::_SqlContainer_default_instance_;
    new (ptr) ::syft::core::store::SqlContainer();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SqlContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SqlContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto}, {}};

static void InitDefaultsscc_info_StorableObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::syft::core::store::_StorableObject_default_instance_;
    new (ptr) ::syft::core::store::StorableObject();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_StorableObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_StorableObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto}, {
      &scc_info_UID_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto.base,
      &scc_info_Any_google_2fprotobuf_2fany_2eproto.base,}};

static void InitDefaultsscc_info_StoreGenericObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::syft::core::store::_StoreGenericObject_default_instance_;
    new (ptr) ::syft::core::store::StoreGenericObject();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_StoreGenericObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_StoreGenericObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto}, {
      &scc_info_StorableObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,
      &scc_info_StoreObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,}};

static void InitDefaultsscc_info_StoreObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::syft::core::store::_StoreObject_default_instance_;
    new (ptr) ::syft::core::store::StoreObject();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_StoreObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_StoreObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto}, {
      &scc_info_Container_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,
      &scc_info_SearchEngine_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2fcore_2fstore_2fstore_5fobject_2eproto[9];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2fcore_2fstore_2fstore_5fobject_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fcore_2fstore_2fstore_5fobject_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fcore_2fstore_2fstore_5fobject_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::StoreGenericObject, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::StoreGenericObject, storable_object_),
  PROTOBUF_FIELD_OFFSET(::syft::core::store::StoreGenericObject, store_object_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::StorableObject, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::StorableObject, id_),
  PROTOBUF_FIELD_OFFSET(::syft::core::store::StorableObject, obj_type_),
  PROTOBUF_FIELD_OFFSET(::syft::core::store::StorableObject, schematic_qualname_),
  PROTOBUF_FIELD_OFFSET(::syft::core::store::StorableObject, data_),
  PROTOBUF_FIELD_OFFSET(::syft::core::store::StorableObject, description_),
  PROTOBUF_FIELD_OFFSET(::syft::core::store::StorableObject, tags_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::StoreObject, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::StoreObject, container_),
  PROTOBUF_FIELD_OFFSET(::syft::core::store::StoreObject, search_engine_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::Container, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::Container, dict_container_),
  PROTOBUF_FIELD_OFFSET(::syft::core::store::Container, sql_container_),
  PROTOBUF_FIELD_OFFSET(::syft::core::store::Container, grid_container_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::SearchEngine, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::DictContainer_DictMappingEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::syft::core::store::DictContainer_DictMappingEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::DictContainer_DictMappingEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::syft::core::store::DictContainer_DictMappingEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::DictContainer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::DictContainer, dict_mapping_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::SqlContainer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::syft::core::store::GridContainer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::syft::core::store::StoreGenericObject)},
  { 7, -1, sizeof(::syft::core::store::StorableObject)},
  { 18, -1, sizeof(::syft::core::store::StoreObject)},
  { 25, -1, sizeof(::syft::core::store::Container)},
  { 33, -1, sizeof(::syft::core::store::SearchEngine)},
  { 38, 45, sizeof(::syft::core::store::DictContainer_DictMappingEntry_DoNotUse)},
  { 47, -1, sizeof(::syft::core::store::DictContainer)},
  { 53, -1, sizeof(::syft::core::store::SqlContainer)},
  { 58, -1, sizeof(::syft::core::store::GridContainer)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::syft::core::store::_StoreGenericObject_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::syft::core::store::_StorableObject_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::syft::core::store::_StoreObject_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::syft::core::store::_Container_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::syft::core::store::_SearchEngine_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::syft::core::store::_DictContainer_DictMappingEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::syft::core::store::_DictContainer_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::syft::core::store::_SqlContainer_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::syft::core::store::_GridContainer_default_instance_),
};

const char descriptor_table_protodef_proto_2fcore_2fstore_2fstore_5fobject_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n#proto/core/store/store_object.proto\022\017s"
  "yft.core.store\032%proto/core/common/common"
  "_object.proto\032\031google/protobuf/any.proto"
  "\"\202\001\n\022StoreGenericObject\0228\n\017storable_obje"
  "ct\030\001 \001(\0132\037.syft.core.store.StorableObjec"
  "t\0222\n\014store_object\030\002 \001(\0132\034.syft.core.stor"
  "e.StoreObject\"\250\001\n\016StorableObject\022!\n\002id\030\001"
  " \001(\0132\025.syft.core.common.UID\022\020\n\010obj_type\030"
  "\002 \001(\t\022\032\n\022schematic_qualname\030\003 \001(\t\022\"\n\004dat"
  "a\030\004 \001(\0132\024.google.protobuf.Any\022\023\n\013descrip"
  "tion\030\005 \001(\t\022\014\n\004tags\030\006 \003(\t\"r\n\013StoreObject\022"
  "-\n\tcontainer\030\001 \001(\0132\032.syft.core.store.Con"
  "tainer\0224\n\rsearch_engine\030\002 \001(\0132\035.syft.cor"
  "e.store.SearchEngine\"\261\001\n\tContainer\0226\n\016di"
  "ct_container\030\001 \001(\0132\036.syft.core.store.Dic"
  "tContainer\0224\n\rsql_container\030\002 \001(\0132\035.syft"
  ".core.store.SqlContainer\0226\n\016grid_contain"
  "er\030\003 \001(\0132\036.syft.core.store.GridContainer"
  "\"\016\n\014SearchEngine\"\240\001\n\rDictContainer\022E\n\014di"
  "ct_mapping\030\001 \003(\0132/.syft.core.store.DictC"
  "ontainer.DictMappingEntry\032H\n\020DictMapping"
  "Entry\022\013\n\003key\030\001 \001(\003\022#\n\005value\030\002 \001(\0132\024.goog"
  "le.protobuf.Any:\0028\001\"\016\n\014SqlContainer\"\017\n\rG"
  "ridContainerb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2fcore_2fstore_2fstore_5fobject_2eproto_deps[2] = {
  &::descriptor_table_google_2fprotobuf_2fany_2eproto,
  &::descriptor_table_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2fcore_2fstore_2fstore_5fobject_2eproto_sccs[9] = {
  &scc_info_Container_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,
  &scc_info_DictContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,
  &scc_info_DictContainer_DictMappingEntry_DoNotUse_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,
  &scc_info_GridContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,
  &scc_info_SearchEngine_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,
  &scc_info_SqlContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,
  &scc_info_StorableObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,
  &scc_info_StoreGenericObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,
  &scc_info_StoreObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fcore_2fstore_2fstore_5fobject_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fcore_2fstore_2fstore_5fobject_2eproto = {
  false, false, descriptor_table_protodef_proto_2fcore_2fstore_2fstore_5fobject_2eproto, "proto/core/store/store_object.proto", 940,
  &descriptor_table_proto_2fcore_2fstore_2fstore_5fobject_2eproto_once, descriptor_table_proto_2fcore_2fstore_2fstore_5fobject_2eproto_sccs, descriptor_table_proto_2fcore_2fstore_2fstore_5fobject_2eproto_deps, 9, 2,
  schemas, file_default_instances, TableStruct_proto_2fcore_2fstore_2fstore_5fobject_2eproto::offsets,
  file_level_metadata_proto_2fcore_2fstore_2fstore_5fobject_2eproto, 9, file_level_enum_descriptors_proto_2fcore_2fstore_2fstore_5fobject_2eproto, file_level_service_descriptors_proto_2fcore_2fstore_2fstore_5fobject_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2fcore_2fstore_2fstore_5fobject_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2fcore_2fstore_2fstore_5fobject_2eproto)), true);
namespace syft {
namespace core {
namespace store {

// ===================================================================

class StoreGenericObject::_Internal {
 public:
  static const ::syft::core::store::StorableObject& storable_object(const StoreGenericObject* msg);
  static const ::syft::core::store::StoreObject& store_object(const StoreGenericObject* msg);
};

const ::syft::core::store::StorableObject&
StoreGenericObject::_Internal::storable_object(const StoreGenericObject* msg) {
  return *msg->storable_object_;
}
const ::syft::core::store::StoreObject&
StoreGenericObject::_Internal::store_object(const StoreGenericObject* msg) {
  return *msg->store_object_;
}
StoreGenericObject::StoreGenericObject(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:syft.core.store.StoreGenericObject)
}
StoreGenericObject::StoreGenericObject(const StoreGenericObject& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_storable_object()) {
    storable_object_ = new ::syft::core::store::StorableObject(*from.storable_object_);
  } else {
    storable_object_ = nullptr;
  }
  if (from._internal_has_store_object()) {
    store_object_ = new ::syft::core::store::StoreObject(*from.store_object_);
  } else {
    store_object_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:syft.core.store.StoreGenericObject)
}

void StoreGenericObject::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_StoreGenericObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base);
  ::memset(&storable_object_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&store_object_) -
      reinterpret_cast<char*>(&storable_object_)) + sizeof(store_object_));
}

StoreGenericObject::~StoreGenericObject() {
  // @@protoc_insertion_point(destructor:syft.core.store.StoreGenericObject)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void StoreGenericObject::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete storable_object_;
  if (this != internal_default_instance()) delete store_object_;
}

void StoreGenericObject::ArenaDtor(void* object) {
  StoreGenericObject* _this = reinterpret_cast< StoreGenericObject* >(object);
  (void)_this;
}
void StoreGenericObject::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void StoreGenericObject::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const StoreGenericObject& StoreGenericObject::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_StoreGenericObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base);
  return *internal_default_instance();
}


void StoreGenericObject::Clear() {
// @@protoc_insertion_point(message_clear_start:syft.core.store.StoreGenericObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && storable_object_ != nullptr) {
    delete storable_object_;
  }
  storable_object_ = nullptr;
  if (GetArena() == nullptr && store_object_ != nullptr) {
    delete store_object_;
  }
  store_object_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StoreGenericObject::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .syft.core.store.StorableObject storable_object = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_storable_object(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .syft.core.store.StoreObject store_object = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_store_object(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* StoreGenericObject::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:syft.core.store.StoreGenericObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .syft.core.store.StorableObject storable_object = 1;
  if (this->has_storable_object()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::storable_object(this), target, stream);
  }

  // .syft.core.store.StoreObject store_object = 2;
  if (this->has_store_object()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::store_object(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syft.core.store.StoreGenericObject)
  return target;
}

size_t StoreGenericObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syft.core.store.StoreGenericObject)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .syft.core.store.StorableObject storable_object = 1;
  if (this->has_storable_object()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *storable_object_);
  }

  // .syft.core.store.StoreObject store_object = 2;
  if (this->has_store_object()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *store_object_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StoreGenericObject::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syft.core.store.StoreGenericObject)
  GOOGLE_DCHECK_NE(&from, this);
  const StoreGenericObject* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<StoreGenericObject>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syft.core.store.StoreGenericObject)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syft.core.store.StoreGenericObject)
    MergeFrom(*source);
  }
}

void StoreGenericObject::MergeFrom(const StoreGenericObject& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syft.core.store.StoreGenericObject)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_storable_object()) {
    _internal_mutable_storable_object()->::syft::core::store::StorableObject::MergeFrom(from._internal_storable_object());
  }
  if (from.has_store_object()) {
    _internal_mutable_store_object()->::syft::core::store::StoreObject::MergeFrom(from._internal_store_object());
  }
}

void StoreGenericObject::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syft.core.store.StoreGenericObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StoreGenericObject::CopyFrom(const StoreGenericObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syft.core.store.StoreGenericObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StoreGenericObject::IsInitialized() const {
  return true;
}

void StoreGenericObject::InternalSwap(StoreGenericObject* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StoreGenericObject, store_object_)
      + sizeof(StoreGenericObject::store_object_)
      - PROTOBUF_FIELD_OFFSET(StoreGenericObject, storable_object_)>(
          reinterpret_cast<char*>(&storable_object_),
          reinterpret_cast<char*>(&other->storable_object_));
}

::PROTOBUF_NAMESPACE_ID::Metadata StoreGenericObject::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class StorableObject::_Internal {
 public:
  static const ::syft::core::common::UID& id(const StorableObject* msg);
  static const PROTOBUF_NAMESPACE_ID::Any& data(const StorableObject* msg);
};

const ::syft::core::common::UID&
StorableObject::_Internal::id(const StorableObject* msg) {
  return *msg->id_;
}
const PROTOBUF_NAMESPACE_ID::Any&
StorableObject::_Internal::data(const StorableObject* msg) {
  return *msg->data_;
}
void StorableObject::clear_id() {
  if (GetArena() == nullptr && id_ != nullptr) {
    delete id_;
  }
  id_ = nullptr;
}
void StorableObject::clear_data() {
  if (GetArena() == nullptr && data_ != nullptr) {
    delete data_;
  }
  data_ = nullptr;
}
StorableObject::StorableObject(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  tags_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:syft.core.store.StorableObject)
}
StorableObject::StorableObject(const StorableObject& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      tags_(from.tags_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  obj_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_obj_type().empty()) {
    obj_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_obj_type(),
      GetArena());
  }
  schematic_qualname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_schematic_qualname().empty()) {
    schematic_qualname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_schematic_qualname(),
      GetArena());
  }
  description_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_description().empty()) {
    description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_description(),
      GetArena());
  }
  if (from._internal_has_id()) {
    id_ = new ::syft::core::common::UID(*from.id_);
  } else {
    id_ = nullptr;
  }
  if (from._internal_has_data()) {
    data_ = new PROTOBUF_NAMESPACE_ID::Any(*from.data_);
  } else {
    data_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:syft.core.store.StorableObject)
}

void StorableObject::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_StorableObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base);
  obj_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  schematic_qualname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  description_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&data_) -
      reinterpret_cast<char*>(&id_)) + sizeof(data_));
}

StorableObject::~StorableObject() {
  // @@protoc_insertion_point(destructor:syft.core.store.StorableObject)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void StorableObject::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  obj_type_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  schematic_qualname_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  description_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete id_;
  if (this != internal_default_instance()) delete data_;
}

void StorableObject::ArenaDtor(void* object) {
  StorableObject* _this = reinterpret_cast< StorableObject* >(object);
  (void)_this;
}
void StorableObject::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void StorableObject::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const StorableObject& StorableObject::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_StorableObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base);
  return *internal_default_instance();
}


void StorableObject::Clear() {
// @@protoc_insertion_point(message_clear_start:syft.core.store.StorableObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  tags_.Clear();
  obj_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  schematic_qualname_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  description_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && id_ != nullptr) {
    delete id_;
  }
  id_ = nullptr;
  if (GetArena() == nullptr && data_ != nullptr) {
    delete data_;
  }
  data_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StorableObject::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .syft.core.common.UID id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_id(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string obj_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_obj_type();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "syft.core.store.StorableObject.obj_type"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string schematic_qualname = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_schematic_qualname();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "syft.core.store.StorableObject.schematic_qualname"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .google.protobuf.Any data = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_data(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string description = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_description();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "syft.core.store.StorableObject.description"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated string tags = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_tags();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "syft.core.store.StorableObject.tags"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* StorableObject::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:syft.core.store.StorableObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .syft.core.common.UID id = 1;
  if (this->has_id()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::id(this), target, stream);
  }

  // string obj_type = 2;
  if (this->obj_type().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_obj_type().data(), static_cast<int>(this->_internal_obj_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "syft.core.store.StorableObject.obj_type");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_obj_type(), target);
  }

  // string schematic_qualname = 3;
  if (this->schematic_qualname().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_schematic_qualname().data(), static_cast<int>(this->_internal_schematic_qualname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "syft.core.store.StorableObject.schematic_qualname");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_schematic_qualname(), target);
  }

  // .google.protobuf.Any data = 4;
  if (this->has_data()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::data(this), target, stream);
  }

  // string description = 5;
  if (this->description().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_description().data(), static_cast<int>(this->_internal_description().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "syft.core.store.StorableObject.description");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_description(), target);
  }

  // repeated string tags = 6;
  for (int i = 0, n = this->_internal_tags_size(); i < n; i++) {
    const auto& s = this->_internal_tags(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "syft.core.store.StorableObject.tags");
    target = stream->WriteString(6, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syft.core.store.StorableObject)
  return target;
}

size_t StorableObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syft.core.store.StorableObject)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string tags = 6;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(tags_.size());
  for (int i = 0, n = tags_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      tags_.Get(i));
  }

  // string obj_type = 2;
  if (this->obj_type().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_obj_type());
  }

  // string schematic_qualname = 3;
  if (this->schematic_qualname().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_schematic_qualname());
  }

  // string description = 5;
  if (this->description().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_description());
  }

  // .syft.core.common.UID id = 1;
  if (this->has_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *id_);
  }

  // .google.protobuf.Any data = 4;
  if (this->has_data()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *data_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StorableObject::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syft.core.store.StorableObject)
  GOOGLE_DCHECK_NE(&from, this);
  const StorableObject* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<StorableObject>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syft.core.store.StorableObject)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syft.core.store.StorableObject)
    MergeFrom(*source);
  }
}

void StorableObject::MergeFrom(const StorableObject& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syft.core.store.StorableObject)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  tags_.MergeFrom(from.tags_);
  if (from.obj_type().size() > 0) {
    _internal_set_obj_type(from._internal_obj_type());
  }
  if (from.schematic_qualname().size() > 0) {
    _internal_set_schematic_qualname(from._internal_schematic_qualname());
  }
  if (from.description().size() > 0) {
    _internal_set_description(from._internal_description());
  }
  if (from.has_id()) {
    _internal_mutable_id()->::syft::core::common::UID::MergeFrom(from._internal_id());
  }
  if (from.has_data()) {
    _internal_mutable_data()->PROTOBUF_NAMESPACE_ID::Any::MergeFrom(from._internal_data());
  }
}

void StorableObject::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syft.core.store.StorableObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StorableObject::CopyFrom(const StorableObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syft.core.store.StorableObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StorableObject::IsInitialized() const {
  return true;
}

void StorableObject::InternalSwap(StorableObject* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  tags_.InternalSwap(&other->tags_);
  obj_type_.Swap(&other->obj_type_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  schematic_qualname_.Swap(&other->schematic_qualname_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  description_.Swap(&other->description_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StorableObject, data_)
      + sizeof(StorableObject::data_)
      - PROTOBUF_FIELD_OFFSET(StorableObject, id_)>(
          reinterpret_cast<char*>(&id_),
          reinterpret_cast<char*>(&other->id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata StorableObject::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class StoreObject::_Internal {
 public:
  static const ::syft::core::store::Container& container(const StoreObject* msg);
  static const ::syft::core::store::SearchEngine& search_engine(const StoreObject* msg);
};

const ::syft::core::store::Container&
StoreObject::_Internal::container(const StoreObject* msg) {
  return *msg->container_;
}
const ::syft::core::store::SearchEngine&
StoreObject::_Internal::search_engine(const StoreObject* msg) {
  return *msg->search_engine_;
}
StoreObject::StoreObject(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:syft.core.store.StoreObject)
}
StoreObject::StoreObject(const StoreObject& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_container()) {
    container_ = new ::syft::core::store::Container(*from.container_);
  } else {
    container_ = nullptr;
  }
  if (from._internal_has_search_engine()) {
    search_engine_ = new ::syft::core::store::SearchEngine(*from.search_engine_);
  } else {
    search_engine_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:syft.core.store.StoreObject)
}

void StoreObject::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_StoreObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base);
  ::memset(&container_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&search_engine_) -
      reinterpret_cast<char*>(&container_)) + sizeof(search_engine_));
}

StoreObject::~StoreObject() {
  // @@protoc_insertion_point(destructor:syft.core.store.StoreObject)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void StoreObject::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete container_;
  if (this != internal_default_instance()) delete search_engine_;
}

void StoreObject::ArenaDtor(void* object) {
  StoreObject* _this = reinterpret_cast< StoreObject* >(object);
  (void)_this;
}
void StoreObject::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void StoreObject::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const StoreObject& StoreObject::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_StoreObject_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base);
  return *internal_default_instance();
}


void StoreObject::Clear() {
// @@protoc_insertion_point(message_clear_start:syft.core.store.StoreObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && container_ != nullptr) {
    delete container_;
  }
  container_ = nullptr;
  if (GetArena() == nullptr && search_engine_ != nullptr) {
    delete search_engine_;
  }
  search_engine_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StoreObject::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .syft.core.store.Container container = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_container(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .syft.core.store.SearchEngine search_engine = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_search_engine(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* StoreObject::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:syft.core.store.StoreObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .syft.core.store.Container container = 1;
  if (this->has_container()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::container(this), target, stream);
  }

  // .syft.core.store.SearchEngine search_engine = 2;
  if (this->has_search_engine()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::search_engine(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syft.core.store.StoreObject)
  return target;
}

size_t StoreObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syft.core.store.StoreObject)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .syft.core.store.Container container = 1;
  if (this->has_container()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *container_);
  }

  // .syft.core.store.SearchEngine search_engine = 2;
  if (this->has_search_engine()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *search_engine_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StoreObject::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syft.core.store.StoreObject)
  GOOGLE_DCHECK_NE(&from, this);
  const StoreObject* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<StoreObject>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syft.core.store.StoreObject)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syft.core.store.StoreObject)
    MergeFrom(*source);
  }
}

void StoreObject::MergeFrom(const StoreObject& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syft.core.store.StoreObject)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_container()) {
    _internal_mutable_container()->::syft::core::store::Container::MergeFrom(from._internal_container());
  }
  if (from.has_search_engine()) {
    _internal_mutable_search_engine()->::syft::core::store::SearchEngine::MergeFrom(from._internal_search_engine());
  }
}

void StoreObject::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syft.core.store.StoreObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StoreObject::CopyFrom(const StoreObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syft.core.store.StoreObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StoreObject::IsInitialized() const {
  return true;
}

void StoreObject::InternalSwap(StoreObject* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StoreObject, search_engine_)
      + sizeof(StoreObject::search_engine_)
      - PROTOBUF_FIELD_OFFSET(StoreObject, container_)>(
          reinterpret_cast<char*>(&container_),
          reinterpret_cast<char*>(&other->container_));
}

::PROTOBUF_NAMESPACE_ID::Metadata StoreObject::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class Container::_Internal {
 public:
  static const ::syft::core::store::DictContainer& dict_container(const Container* msg);
  static const ::syft::core::store::SqlContainer& sql_container(const Container* msg);
  static const ::syft::core::store::GridContainer& grid_container(const Container* msg);
};

const ::syft::core::store::DictContainer&
Container::_Internal::dict_container(const Container* msg) {
  return *msg->dict_container_;
}
const ::syft::core::store::SqlContainer&
Container::_Internal::sql_container(const Container* msg) {
  return *msg->sql_container_;
}
const ::syft::core::store::GridContainer&
Container::_Internal::grid_container(const Container* msg) {
  return *msg->grid_container_;
}
Container::Container(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:syft.core.store.Container)
}
Container::Container(const Container& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_dict_container()) {
    dict_container_ = new ::syft::core::store::DictContainer(*from.dict_container_);
  } else {
    dict_container_ = nullptr;
  }
  if (from._internal_has_sql_container()) {
    sql_container_ = new ::syft::core::store::SqlContainer(*from.sql_container_);
  } else {
    sql_container_ = nullptr;
  }
  if (from._internal_has_grid_container()) {
    grid_container_ = new ::syft::core::store::GridContainer(*from.grid_container_);
  } else {
    grid_container_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:syft.core.store.Container)
}

void Container::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Container_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base);
  ::memset(&dict_container_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&grid_container_) -
      reinterpret_cast<char*>(&dict_container_)) + sizeof(grid_container_));
}

Container::~Container() {
  // @@protoc_insertion_point(destructor:syft.core.store.Container)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Container::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete dict_container_;
  if (this != internal_default_instance()) delete sql_container_;
  if (this != internal_default_instance()) delete grid_container_;
}

void Container::ArenaDtor(void* object) {
  Container* _this = reinterpret_cast< Container* >(object);
  (void)_this;
}
void Container::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Container::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Container& Container::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Container_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base);
  return *internal_default_instance();
}


void Container::Clear() {
// @@protoc_insertion_point(message_clear_start:syft.core.store.Container)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && dict_container_ != nullptr) {
    delete dict_container_;
  }
  dict_container_ = nullptr;
  if (GetArena() == nullptr && sql_container_ != nullptr) {
    delete sql_container_;
  }
  sql_container_ = nullptr;
  if (GetArena() == nullptr && grid_container_ != nullptr) {
    delete grid_container_;
  }
  grid_container_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Container::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .syft.core.store.DictContainer dict_container = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_dict_container(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .syft.core.store.SqlContainer sql_container = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_sql_container(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .syft.core.store.GridContainer grid_container = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_grid_container(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Container::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:syft.core.store.Container)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .syft.core.store.DictContainer dict_container = 1;
  if (this->has_dict_container()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::dict_container(this), target, stream);
  }

  // .syft.core.store.SqlContainer sql_container = 2;
  if (this->has_sql_container()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::sql_container(this), target, stream);
  }

  // .syft.core.store.GridContainer grid_container = 3;
  if (this->has_grid_container()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::grid_container(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syft.core.store.Container)
  return target;
}

size_t Container::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syft.core.store.Container)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .syft.core.store.DictContainer dict_container = 1;
  if (this->has_dict_container()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *dict_container_);
  }

  // .syft.core.store.SqlContainer sql_container = 2;
  if (this->has_sql_container()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *sql_container_);
  }

  // .syft.core.store.GridContainer grid_container = 3;
  if (this->has_grid_container()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *grid_container_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Container::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syft.core.store.Container)
  GOOGLE_DCHECK_NE(&from, this);
  const Container* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Container>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syft.core.store.Container)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syft.core.store.Container)
    MergeFrom(*source);
  }
}

void Container::MergeFrom(const Container& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syft.core.store.Container)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_dict_container()) {
    _internal_mutable_dict_container()->::syft::core::store::DictContainer::MergeFrom(from._internal_dict_container());
  }
  if (from.has_sql_container()) {
    _internal_mutable_sql_container()->::syft::core::store::SqlContainer::MergeFrom(from._internal_sql_container());
  }
  if (from.has_grid_container()) {
    _internal_mutable_grid_container()->::syft::core::store::GridContainer::MergeFrom(from._internal_grid_container());
  }
}

void Container::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syft.core.store.Container)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Container::CopyFrom(const Container& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syft.core.store.Container)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Container::IsInitialized() const {
  return true;
}

void Container::InternalSwap(Container* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Container, grid_container_)
      + sizeof(Container::grid_container_)
      - PROTOBUF_FIELD_OFFSET(Container, dict_container_)>(
          reinterpret_cast<char*>(&dict_container_),
          reinterpret_cast<char*>(&other->dict_container_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Container::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class SearchEngine::_Internal {
 public:
};

SearchEngine::SearchEngine(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:syft.core.store.SearchEngine)
}
SearchEngine::SearchEngine(const SearchEngine& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:syft.core.store.SearchEngine)
}

void SearchEngine::SharedCtor() {
}

SearchEngine::~SearchEngine() {
  // @@protoc_insertion_point(destructor:syft.core.store.SearchEngine)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SearchEngine::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void SearchEngine::ArenaDtor(void* object) {
  SearchEngine* _this = reinterpret_cast< SearchEngine* >(object);
  (void)_this;
}
void SearchEngine::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SearchEngine::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SearchEngine& SearchEngine::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SearchEngine_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base);
  return *internal_default_instance();
}


void SearchEngine::Clear() {
// @@protoc_insertion_point(message_clear_start:syft.core.store.SearchEngine)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SearchEngine::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SearchEngine::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:syft.core.store.SearchEngine)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syft.core.store.SearchEngine)
  return target;
}

size_t SearchEngine::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syft.core.store.SearchEngine)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SearchEngine::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syft.core.store.SearchEngine)
  GOOGLE_DCHECK_NE(&from, this);
  const SearchEngine* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SearchEngine>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syft.core.store.SearchEngine)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syft.core.store.SearchEngine)
    MergeFrom(*source);
  }
}

void SearchEngine::MergeFrom(const SearchEngine& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syft.core.store.SearchEngine)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void SearchEngine::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syft.core.store.SearchEngine)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SearchEngine::CopyFrom(const SearchEngine& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syft.core.store.SearchEngine)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SearchEngine::IsInitialized() const {
  return true;
}

void SearchEngine::InternalSwap(SearchEngine* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SearchEngine::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

DictContainer_DictMappingEntry_DoNotUse::DictContainer_DictMappingEntry_DoNotUse() {}
DictContainer_DictMappingEntry_DoNotUse::DictContainer_DictMappingEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void DictContainer_DictMappingEntry_DoNotUse::MergeFrom(const DictContainer_DictMappingEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata DictContainer_DictMappingEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void DictContainer_DictMappingEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

class DictContainer::_Internal {
 public:
};

void DictContainer::clear_dict_mapping() {
  dict_mapping_.Clear();
}
DictContainer::DictContainer(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  dict_mapping_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:syft.core.store.DictContainer)
}
DictContainer::DictContainer(const DictContainer& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  dict_mapping_.MergeFrom(from.dict_mapping_);
  // @@protoc_insertion_point(copy_constructor:syft.core.store.DictContainer)
}

void DictContainer::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_DictContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base);
}

DictContainer::~DictContainer() {
  // @@protoc_insertion_point(destructor:syft.core.store.DictContainer)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void DictContainer::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void DictContainer::ArenaDtor(void* object) {
  DictContainer* _this = reinterpret_cast< DictContainer* >(object);
  (void)_this;
}
void DictContainer::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DictContainer::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DictContainer& DictContainer::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DictContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base);
  return *internal_default_instance();
}


void DictContainer::Clear() {
// @@protoc_insertion_point(message_clear_start:syft.core.store.DictContainer)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  dict_mapping_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DictContainer::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // map<int64, .google.protobuf.Any> dict_mapping = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&dict_mapping_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DictContainer::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:syft.core.store.DictContainer)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<int64, .google.protobuf.Any> dict_mapping = 1;
  if (!this->_internal_dict_mapping().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int64, PROTOBUF_NAMESPACE_ID::Any >::const_pointer
        ConstPtr;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::SortItem< ::PROTOBUF_NAMESPACE_ID::int64, ConstPtr > SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByFirstField<SortItem> Less;

    if (stream->IsSerializationDeterministic() &&
        this->_internal_dict_mapping().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_dict_mapping().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int64, PROTOBUF_NAMESPACE_ID::Any >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int64, PROTOBUF_NAMESPACE_ID::Any >::const_iterator
          it = this->_internal_dict_mapping().begin();
          it != this->_internal_dict_mapping().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = DictContainer_DictMappingEntry_DoNotUse::Funcs::InternalSerialize(1, items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second, target, stream);
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int64, PROTOBUF_NAMESPACE_ID::Any >::const_iterator
          it = this->_internal_dict_mapping().begin();
          it != this->_internal_dict_mapping().end(); ++it) {
        target = DictContainer_DictMappingEntry_DoNotUse::Funcs::InternalSerialize(1, it->first, it->second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syft.core.store.DictContainer)
  return target;
}

size_t DictContainer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syft.core.store.DictContainer)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<int64, .google.protobuf.Any> dict_mapping = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_dict_mapping_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int64, PROTOBUF_NAMESPACE_ID::Any >::const_iterator
      it = this->_internal_dict_mapping().begin();
      it != this->_internal_dict_mapping().end(); ++it) {
    total_size += DictContainer_DictMappingEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DictContainer::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syft.core.store.DictContainer)
  GOOGLE_DCHECK_NE(&from, this);
  const DictContainer* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<DictContainer>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syft.core.store.DictContainer)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syft.core.store.DictContainer)
    MergeFrom(*source);
  }
}

void DictContainer::MergeFrom(const DictContainer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syft.core.store.DictContainer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  dict_mapping_.MergeFrom(from.dict_mapping_);
}

void DictContainer::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syft.core.store.DictContainer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DictContainer::CopyFrom(const DictContainer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syft.core.store.DictContainer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DictContainer::IsInitialized() const {
  return true;
}

void DictContainer::InternalSwap(DictContainer* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  dict_mapping_.Swap(&other->dict_mapping_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DictContainer::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class SqlContainer::_Internal {
 public:
};

SqlContainer::SqlContainer(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:syft.core.store.SqlContainer)
}
SqlContainer::SqlContainer(const SqlContainer& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:syft.core.store.SqlContainer)
}

void SqlContainer::SharedCtor() {
}

SqlContainer::~SqlContainer() {
  // @@protoc_insertion_point(destructor:syft.core.store.SqlContainer)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SqlContainer::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void SqlContainer::ArenaDtor(void* object) {
  SqlContainer* _this = reinterpret_cast< SqlContainer* >(object);
  (void)_this;
}
void SqlContainer::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SqlContainer::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SqlContainer& SqlContainer::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SqlContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base);
  return *internal_default_instance();
}


void SqlContainer::Clear() {
// @@protoc_insertion_point(message_clear_start:syft.core.store.SqlContainer)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SqlContainer::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SqlContainer::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:syft.core.store.SqlContainer)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syft.core.store.SqlContainer)
  return target;
}

size_t SqlContainer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syft.core.store.SqlContainer)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SqlContainer::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syft.core.store.SqlContainer)
  GOOGLE_DCHECK_NE(&from, this);
  const SqlContainer* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SqlContainer>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syft.core.store.SqlContainer)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syft.core.store.SqlContainer)
    MergeFrom(*source);
  }
}

void SqlContainer::MergeFrom(const SqlContainer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syft.core.store.SqlContainer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void SqlContainer::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syft.core.store.SqlContainer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SqlContainer::CopyFrom(const SqlContainer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syft.core.store.SqlContainer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SqlContainer::IsInitialized() const {
  return true;
}

void SqlContainer::InternalSwap(SqlContainer* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SqlContainer::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GridContainer::_Internal {
 public:
};

GridContainer::GridContainer(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:syft.core.store.GridContainer)
}
GridContainer::GridContainer(const GridContainer& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:syft.core.store.GridContainer)
}

void GridContainer::SharedCtor() {
}

GridContainer::~GridContainer() {
  // @@protoc_insertion_point(destructor:syft.core.store.GridContainer)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GridContainer::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GridContainer::ArenaDtor(void* object) {
  GridContainer* _this = reinterpret_cast< GridContainer* >(object);
  (void)_this;
}
void GridContainer::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GridContainer::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GridContainer& GridContainer::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GridContainer_proto_2fcore_2fstore_2fstore_5fobject_2eproto.base);
  return *internal_default_instance();
}


void GridContainer::Clear() {
// @@protoc_insertion_point(message_clear_start:syft.core.store.GridContainer)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GridContainer::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GridContainer::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:syft.core.store.GridContainer)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syft.core.store.GridContainer)
  return target;
}

size_t GridContainer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syft.core.store.GridContainer)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GridContainer::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syft.core.store.GridContainer)
  GOOGLE_DCHECK_NE(&from, this);
  const GridContainer* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GridContainer>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syft.core.store.GridContainer)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syft.core.store.GridContainer)
    MergeFrom(*source);
  }
}

void GridContainer::MergeFrom(const GridContainer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syft.core.store.GridContainer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void GridContainer::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syft.core.store.GridContainer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GridContainer::CopyFrom(const GridContainer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syft.core.store.GridContainer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GridContainer::IsInitialized() const {
  return true;
}

void GridContainer::InternalSwap(GridContainer* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GridContainer::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace store
}  // namespace core
}  // namespace syft
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::syft::core::store::StoreGenericObject* Arena::CreateMaybeMessage< ::syft::core::store::StoreGenericObject >(Arena* arena) {
  return Arena::CreateMessageInternal< ::syft::core::store::StoreGenericObject >(arena);
}
template<> PROTOBUF_NOINLINE ::syft::core::store::StorableObject* Arena::CreateMaybeMessage< ::syft::core::store::StorableObject >(Arena* arena) {
  return Arena::CreateMessageInternal< ::syft::core::store::StorableObject >(arena);
}
template<> PROTOBUF_NOINLINE ::syft::core::store::StoreObject* Arena::CreateMaybeMessage< ::syft::core::store::StoreObject >(Arena* arena) {
  return Arena::CreateMessageInternal< ::syft::core::store::StoreObject >(arena);
}
template<> PROTOBUF_NOINLINE ::syft::core::store::Container* Arena::CreateMaybeMessage< ::syft::core::store::Container >(Arena* arena) {
  return Arena::CreateMessageInternal< ::syft::core::store::Container >(arena);
}
template<> PROTOBUF_NOINLINE ::syft::core::store::SearchEngine* Arena::CreateMaybeMessage< ::syft::core::store::SearchEngine >(Arena* arena) {
  return Arena::CreateMessageInternal< ::syft::core::store::SearchEngine >(arena);
}
template<> PROTOBUF_NOINLINE ::syft::core::store::DictContainer_DictMappingEntry_DoNotUse* Arena::CreateMaybeMessage< ::syft::core::store::DictContainer_DictMappingEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::syft::core::store::DictContainer_DictMappingEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::syft::core::store::DictContainer* Arena::CreateMaybeMessage< ::syft::core::store::DictContainer >(Arena* arena) {
  return Arena::CreateMessageInternal< ::syft::core::store::DictContainer >(arena);
}
template<> PROTOBUF_NOINLINE ::syft::core::store::SqlContainer* Arena::CreateMaybeMessage< ::syft::core::store::SqlContainer >(Arena* arena) {
  return Arena::CreateMessageInternal< ::syft::core::store::SqlContainer >(arena);
}
template<> PROTOBUF_NOINLINE ::syft::core::store::GridContainer* Arena::CreateMaybeMessage< ::syft::core::store::GridContainer >(Arena* arena) {
  return Arena::CreateMessageInternal< ::syft::core::store::GridContainer >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
