// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/lib/generic_tensor.proto

#include "proto/lib/generic_tensor.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_proto_2flib_2fnumpy_2ftensor_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TensorProto_proto_2flib_2fnumpy_2ftensor_2eproto;
namespace syft {
namespace lib {
class GenericTensorDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GenericTensor> _instance;
} _GenericTensor_default_instance_;
}  // namespace lib
}  // namespace syft
static void InitDefaultsscc_info_GenericTensor_proto_2flib_2fgeneric_5ftensor_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::syft::lib::_GenericTensor_default_instance_;
    new (ptr) ::syft::lib::GenericTensor();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_GenericTensor_proto_2flib_2fgeneric_5ftensor_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_GenericTensor_proto_2flib_2fgeneric_5ftensor_2eproto}, {
      &scc_info_TensorProto_proto_2flib_2fnumpy_2ftensor_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2flib_2fgeneric_5ftensor_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2flib_2fgeneric_5ftensor_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2flib_2fgeneric_5ftensor_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2flib_2fgeneric_5ftensor_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::syft::lib::GenericTensor, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::syft::lib::GenericTensor, numpy_tensor_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::syft::lib::GenericTensor)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::syft::lib::_GenericTensor_default_instance_),
};

const char descriptor_table_protodef_proto_2flib_2fgeneric_5ftensor_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036proto/lib/generic_tensor.proto\022\010syft.l"
  "ib\032\034proto/lib/numpy/tensor.proto\"B\n\rGene"
  "ricTensor\0221\n\014numpy_tensor\030\001 \001(\0132\033.syft.l"
  "ib.numpy.TensorProtob\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2flib_2fgeneric_5ftensor_2eproto_deps[1] = {
  &::descriptor_table_proto_2flib_2fnumpy_2ftensor_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2flib_2fgeneric_5ftensor_2eproto_sccs[1] = {
  &scc_info_GenericTensor_proto_2flib_2fgeneric_5ftensor_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2flib_2fgeneric_5ftensor_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2flib_2fgeneric_5ftensor_2eproto = {
  false, false, descriptor_table_protodef_proto_2flib_2fgeneric_5ftensor_2eproto, "proto/lib/generic_tensor.proto", 148,
  &descriptor_table_proto_2flib_2fgeneric_5ftensor_2eproto_once, descriptor_table_proto_2flib_2fgeneric_5ftensor_2eproto_sccs, descriptor_table_proto_2flib_2fgeneric_5ftensor_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_proto_2flib_2fgeneric_5ftensor_2eproto::offsets,
  file_level_metadata_proto_2flib_2fgeneric_5ftensor_2eproto, 1, file_level_enum_descriptors_proto_2flib_2fgeneric_5ftensor_2eproto, file_level_service_descriptors_proto_2flib_2fgeneric_5ftensor_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2flib_2fgeneric_5ftensor_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2flib_2fgeneric_5ftensor_2eproto)), true);
namespace syft {
namespace lib {

// ===================================================================

class GenericTensor::_Internal {
 public:
  static const ::syft::lib::numpy::TensorProto& numpy_tensor(const GenericTensor* msg);
};

const ::syft::lib::numpy::TensorProto&
GenericTensor::_Internal::numpy_tensor(const GenericTensor* msg) {
  return *msg->numpy_tensor_;
}
void GenericTensor::clear_numpy_tensor() {
  if (GetArena() == nullptr && numpy_tensor_ != nullptr) {
    delete numpy_tensor_;
  }
  numpy_tensor_ = nullptr;
}
GenericTensor::GenericTensor(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:syft.lib.GenericTensor)
}
GenericTensor::GenericTensor(const GenericTensor& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_numpy_tensor()) {
    numpy_tensor_ = new ::syft::lib::numpy::TensorProto(*from.numpy_tensor_);
  } else {
    numpy_tensor_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:syft.lib.GenericTensor)
}

void GenericTensor::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GenericTensor_proto_2flib_2fgeneric_5ftensor_2eproto.base);
  numpy_tensor_ = nullptr;
}

GenericTensor::~GenericTensor() {
  // @@protoc_insertion_point(destructor:syft.lib.GenericTensor)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GenericTensor::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete numpy_tensor_;
}

void GenericTensor::ArenaDtor(void* object) {
  GenericTensor* _this = reinterpret_cast< GenericTensor* >(object);
  (void)_this;
}
void GenericTensor::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GenericTensor::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GenericTensor& GenericTensor::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GenericTensor_proto_2flib_2fgeneric_5ftensor_2eproto.base);
  return *internal_default_instance();
}


void GenericTensor::Clear() {
// @@protoc_insertion_point(message_clear_start:syft.lib.GenericTensor)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && numpy_tensor_ != nullptr) {
    delete numpy_tensor_;
  }
  numpy_tensor_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GenericTensor::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .syft.lib.numpy.TensorProto numpy_tensor = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_numpy_tensor(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GenericTensor::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:syft.lib.GenericTensor)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .syft.lib.numpy.TensorProto numpy_tensor = 1;
  if (this->has_numpy_tensor()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::numpy_tensor(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syft.lib.GenericTensor)
  return target;
}

size_t GenericTensor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syft.lib.GenericTensor)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .syft.lib.numpy.TensorProto numpy_tensor = 1;
  if (this->has_numpy_tensor()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *numpy_tensor_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GenericTensor::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syft.lib.GenericTensor)
  GOOGLE_DCHECK_NE(&from, this);
  const GenericTensor* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GenericTensor>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syft.lib.GenericTensor)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syft.lib.GenericTensor)
    MergeFrom(*source);
  }
}

void GenericTensor::MergeFrom(const GenericTensor& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syft.lib.GenericTensor)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_numpy_tensor()) {
    _internal_mutable_numpy_tensor()->::syft::lib::numpy::TensorProto::MergeFrom(from._internal_numpy_tensor());
  }
}

void GenericTensor::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syft.lib.GenericTensor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GenericTensor::CopyFrom(const GenericTensor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syft.lib.GenericTensor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GenericTensor::IsInitialized() const {
  return true;
}

void GenericTensor::InternalSwap(GenericTensor* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(numpy_tensor_, other->numpy_tensor_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GenericTensor::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace lib
}  // namespace syft
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::syft::lib::GenericTensor* Arena::CreateMaybeMessage< ::syft::lib::GenericTensor >(Arena* arena) {
  return Arena::CreateMessageInternal< ::syft::lib::GenericTensor >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
