// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/core/core_object.proto

#include "proto/core/core_object.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_CommonObject_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto;
namespace syft {
namespace core {
class CoreObjectDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CoreObject> _instance;
} _CoreObject_default_instance_;
}  // namespace core
}  // namespace syft
static void InitDefaultsscc_info_CoreObject_proto_2fcore_2fcore_5fobject_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::syft::core::_CoreObject_default_instance_;
    new (ptr) ::syft::core::CoreObject();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_CoreObject_proto_2fcore_2fcore_5fobject_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_CoreObject_proto_2fcore_2fcore_5fobject_2eproto}, {
      &scc_info_CommonObject_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2fcore_2fcore_5fobject_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2fcore_2fcore_5fobject_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fcore_2fcore_5fobject_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fcore_2fcore_5fobject_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::syft::core::CoreObject, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::syft::core::CoreObject, common_object_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::syft::core::CoreObject)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::syft::core::_CoreObject_default_instance_),
};

const char descriptor_table_protodef_proto_2fcore_2fcore_5fobject_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\034proto/core/core_object.proto\022\tsyft.cor"
  "e\032%proto/core/common/common_object.proto"
  "\"C\n\nCoreObject\0225\n\rcommon_object\030\001 \001(\0132\036."
  "syft.core.common.CommonObjectb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2fcore_2fcore_5fobject_2eproto_deps[1] = {
  &::descriptor_table_proto_2fcore_2fcommon_2fcommon_5fobject_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2fcore_2fcore_5fobject_2eproto_sccs[1] = {
  &scc_info_CoreObject_proto_2fcore_2fcore_5fobject_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fcore_2fcore_5fobject_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fcore_2fcore_5fobject_2eproto = {
  false, false, descriptor_table_protodef_proto_2fcore_2fcore_5fobject_2eproto, "proto/core/core_object.proto", 157,
  &descriptor_table_proto_2fcore_2fcore_5fobject_2eproto_once, descriptor_table_proto_2fcore_2fcore_5fobject_2eproto_sccs, descriptor_table_proto_2fcore_2fcore_5fobject_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_proto_2fcore_2fcore_5fobject_2eproto::offsets,
  file_level_metadata_proto_2fcore_2fcore_5fobject_2eproto, 1, file_level_enum_descriptors_proto_2fcore_2fcore_5fobject_2eproto, file_level_service_descriptors_proto_2fcore_2fcore_5fobject_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2fcore_2fcore_5fobject_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2fcore_2fcore_5fobject_2eproto)), true);
namespace syft {
namespace core {

// ===================================================================

class CoreObject::_Internal {
 public:
  static const ::syft::core::common::CommonObject& common_object(const CoreObject* msg);
};

const ::syft::core::common::CommonObject&
CoreObject::_Internal::common_object(const CoreObject* msg) {
  return *msg->common_object_;
}
void CoreObject::clear_common_object() {
  if (GetArena() == nullptr && common_object_ != nullptr) {
    delete common_object_;
  }
  common_object_ = nullptr;
}
CoreObject::CoreObject(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:syft.core.CoreObject)
}
CoreObject::CoreObject(const CoreObject& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_common_object()) {
    common_object_ = new ::syft::core::common::CommonObject(*from.common_object_);
  } else {
    common_object_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:syft.core.CoreObject)
}

void CoreObject::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_CoreObject_proto_2fcore_2fcore_5fobject_2eproto.base);
  common_object_ = nullptr;
}

CoreObject::~CoreObject() {
  // @@protoc_insertion_point(destructor:syft.core.CoreObject)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CoreObject::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete common_object_;
}

void CoreObject::ArenaDtor(void* object) {
  CoreObject* _this = reinterpret_cast< CoreObject* >(object);
  (void)_this;
}
void CoreObject::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CoreObject::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CoreObject& CoreObject::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CoreObject_proto_2fcore_2fcore_5fobject_2eproto.base);
  return *internal_default_instance();
}


void CoreObject::Clear() {
// @@protoc_insertion_point(message_clear_start:syft.core.CoreObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && common_object_ != nullptr) {
    delete common_object_;
  }
  common_object_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CoreObject::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .syft.core.common.CommonObject common_object = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_common_object(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CoreObject::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:syft.core.CoreObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .syft.core.common.CommonObject common_object = 1;
  if (this->has_common_object()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::common_object(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:syft.core.CoreObject)
  return target;
}

size_t CoreObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:syft.core.CoreObject)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .syft.core.common.CommonObject common_object = 1;
  if (this->has_common_object()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *common_object_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CoreObject::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:syft.core.CoreObject)
  GOOGLE_DCHECK_NE(&from, this);
  const CoreObject* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CoreObject>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:syft.core.CoreObject)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:syft.core.CoreObject)
    MergeFrom(*source);
  }
}

void CoreObject::MergeFrom(const CoreObject& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:syft.core.CoreObject)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_common_object()) {
    _internal_mutable_common_object()->::syft::core::common::CommonObject::MergeFrom(from._internal_common_object());
  }
}

void CoreObject::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:syft.core.CoreObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CoreObject::CopyFrom(const CoreObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:syft.core.CoreObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CoreObject::IsInitialized() const {
  return true;
}

void CoreObject::InternalSwap(CoreObject* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(common_object_, other->common_object_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CoreObject::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace core
}  // namespace syft
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::syft::core::CoreObject* Arena::CreateMaybeMessage< ::syft::core::CoreObject >(Arena* arena) {
  return Arena::CreateMessageInternal< ::syft::core::CoreObject >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
