// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/core/core_object.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fcore_2fcore_5fobject_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fcore_2fcore_5fobject_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "proto/core/common/common_object.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fcore_2fcore_5fobject_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fcore_2fcore_5fobject_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fcore_2fcore_5fobject_2eproto;
namespace syft {
namespace core {
class CoreObject;
class CoreObjectDefaultTypeInternal;
extern CoreObjectDefaultTypeInternal _CoreObject_default_instance_;
}  // namespace core
}  // namespace syft
PROTOBUF_NAMESPACE_OPEN
template<> ::syft::core::CoreObject* Arena::CreateMaybeMessage<::syft::core::CoreObject>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace syft {
namespace core {

// ===================================================================

class CoreObject PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:syft.core.CoreObject) */ {
 public:
  inline CoreObject() : CoreObject(nullptr) {}
  virtual ~CoreObject();

  CoreObject(const CoreObject& from);
  CoreObject(CoreObject&& from) noexcept
    : CoreObject() {
    *this = ::std::move(from);
  }

  inline CoreObject& operator=(const CoreObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline CoreObject& operator=(CoreObject&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CoreObject& default_instance();

  static inline const CoreObject* internal_default_instance() {
    return reinterpret_cast<const CoreObject*>(
               &_CoreObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CoreObject& a, CoreObject& b) {
    a.Swap(&b);
  }
  inline void Swap(CoreObject* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CoreObject* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CoreObject* New() const final {
    return CreateMaybeMessage<CoreObject>(nullptr);
  }

  CoreObject* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CoreObject>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CoreObject& from);
  void MergeFrom(const CoreObject& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CoreObject* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "syft.core.CoreObject";
  }
  protected:
  explicit CoreObject(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fcore_2fcore_5fobject_2eproto);
    return ::descriptor_table_proto_2fcore_2fcore_5fobject_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommonObjectFieldNumber = 1,
  };
  // .syft.core.common.CommonObject common_object = 1;
  bool has_common_object() const;
  private:
  bool _internal_has_common_object() const;
  public:
  void clear_common_object();
  const ::syft::core::common::CommonObject& common_object() const;
  ::syft::core::common::CommonObject* release_common_object();
  ::syft::core::common::CommonObject* mutable_common_object();
  void set_allocated_common_object(::syft::core::common::CommonObject* common_object);
  private:
  const ::syft::core::common::CommonObject& _internal_common_object() const;
  ::syft::core::common::CommonObject* _internal_mutable_common_object();
  public:
  void unsafe_arena_set_allocated_common_object(
      ::syft::core::common::CommonObject* common_object);
  ::syft::core::common::CommonObject* unsafe_arena_release_common_object();

  // @@protoc_insertion_point(class_scope:syft.core.CoreObject)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::syft::core::common::CommonObject* common_object_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcore_2fcore_5fobject_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CoreObject

// .syft.core.common.CommonObject common_object = 1;
inline bool CoreObject::_internal_has_common_object() const {
  return this != internal_default_instance() && common_object_ != nullptr;
}
inline bool CoreObject::has_common_object() const {
  return _internal_has_common_object();
}
inline const ::syft::core::common::CommonObject& CoreObject::_internal_common_object() const {
  const ::syft::core::common::CommonObject* p = common_object_;
  return p != nullptr ? *p : reinterpret_cast<const ::syft::core::common::CommonObject&>(
      ::syft::core::common::_CommonObject_default_instance_);
}
inline const ::syft::core::common::CommonObject& CoreObject::common_object() const {
  // @@protoc_insertion_point(field_get:syft.core.CoreObject.common_object)
  return _internal_common_object();
}
inline void CoreObject::unsafe_arena_set_allocated_common_object(
    ::syft::core::common::CommonObject* common_object) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(common_object_);
  }
  common_object_ = common_object;
  if (common_object) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:syft.core.CoreObject.common_object)
}
inline ::syft::core::common::CommonObject* CoreObject::release_common_object() {
  
  ::syft::core::common::CommonObject* temp = common_object_;
  common_object_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::syft::core::common::CommonObject* CoreObject::unsafe_arena_release_common_object() {
  // @@protoc_insertion_point(field_release:syft.core.CoreObject.common_object)
  
  ::syft::core::common::CommonObject* temp = common_object_;
  common_object_ = nullptr;
  return temp;
}
inline ::syft::core::common::CommonObject* CoreObject::_internal_mutable_common_object() {
  
  if (common_object_ == nullptr) {
    auto* p = CreateMaybeMessage<::syft::core::common::CommonObject>(GetArena());
    common_object_ = p;
  }
  return common_object_;
}
inline ::syft::core::common::CommonObject* CoreObject::mutable_common_object() {
  // @@protoc_insertion_point(field_mutable:syft.core.CoreObject.common_object)
  return _internal_mutable_common_object();
}
inline void CoreObject::set_allocated_common_object(::syft::core::common::CommonObject* common_object) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(common_object_);
  }
  if (common_object) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(common_object)->GetArena();
    if (message_arena != submessage_arena) {
      common_object = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, common_object, submessage_arena);
    }
    
  } else {
    
  }
  common_object_ = common_object;
  // @@protoc_insertion_point(field_set_allocated:syft.core.CoreObject.common_object)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace core
}  // namespace syft

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fcore_2fcore_5fobject_2eproto
