name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
         sudo apt-get -qq update
         sudo apt-get install -y build-essential cmake
         sudo apt-get install -qq valgrind
         sudo apt install -y clang clang-format
         sudo apt-get install -qq automake
         sudo apt-get install -qq autoconf
         sudo apt install -y libtool
         sudo apt install libtool-bin
         sudo apt-get install -y pkg-config
         sudo apt-get install -y texinfo
         sudo apt install libsubunit-dev
  
    - name: Before script
      run: |
          mkdir build
          automake --version
          autoconf --version
          libtool --version
          pkg-config --version

    - name: Lint
      run: bash ./check_code_format.sh
      
    - name: Build
      run: |
          cd build
          cmake ..
          make
