name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install -y build-essential cmake
          sudo apt install -y clang-format
          sudo apt install automake
          sudo apt install autoconf
          sudo apt install -y libtool
          sudo apt install libtool-bin
          sudo apt install -y pkg-config
          sudo apt install -y texinfo
          sudo apt install libsubunit-dev
  
    - name: Before script
      run: |
          mkdir build
          automake --version
          autoconf --version
          libtool --version
          pkg-config --version

    - name: Lint
      run: bash ./check_code_format.sh
      
    - name: Build
      run: |
          cd build
          cmake ..
          make
